import Head from "next/head";
import CallToAction from "../components/CallToAction";
import DisplayUsage from "../components/DisplayUsage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fylo Data Storage Component</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen backgroundImage">
        <div className="flex flex-col md:flex-row min-h-screen justify-center items-center">
          <div className="flex flex-col lg:flex-row lg:items-end items-center justify-center 2xl:w-2/4 xl:w-2/4 lg:w-3/4 w-full">
            <CallToAction />
            <DisplayUsage />
          </div>
        </div>
      </main>
    </>
  );
}
