import Head from "next/head";
import CallToAction from "../components/CallToAction";
import DisplayUsage from "../components/DisplayUsage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fylo Data Storage Component</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen backgroundImage">
        <div className="flex flex-col  min-h-screen justify-center items-center">
          <CallToAction />
          <DisplayUsage />
        </div>
      </main>
    </>
  );
}
